config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "places#index"
  resources :users, only: :show
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :user

  validates :content, presence: true
end

app/models/place.rb
class Place < ApplicationRecord

  validates :title, presence: true
  validates :concept, presence: true
  validates :image, presence: true

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

validates :name, presence: true

has_many :places
has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to place_path(@comment.place)
    else
      @place = @comment.place
      @comments = @place.comments
      render "places/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id,place_id: params[:place_id] )
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to root_path 
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :concept, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @places = @user.places
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HappyMyanmar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "投稿する", new_place_path, class: :nav__btn %> 
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © HAPPY MYANMAR All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with model: place, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "名称" %><br />
    <%= f.text_field :title, id:"place_title" %>
  </div>

  <div class="field">
    <%= f.label :concept, "案内" %><br />
    <%= f.text_area :concept, class: :form__text, id:"place_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"place_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div class="card">
  <%= link_to image_tag(place.image, class: :card__img ), place_path(place.id), method: :get %>
  <div class="card__body">
    <%= link_to place.title, place_path(place.id), method: :get, class: :card__title%>
    <%= link_to "by #{place.user.name}", user_path(place.user.id), class: :card__user %>
  </div>
</div>

app/views/places/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "こんにちは、#{current_user.name}さん", user_path(current_user) %>
    <% else %>
        <% link_to "新規登録", new_user_registration_path, class: :greeting__link%>
      </div> 
    <% end %>
    <div class="card__wrapper">
      <%# <%= render partial: "place", collection: @places %> 
    </div>
  </div>
</main>

app/views/places/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: "form", locals: {place: @place} %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= "プロトタイプのタイトル"%>
      </p>
      <%= link_to "by プロトタイプの投稿者", root_path, class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <%= link_to "編集する", root_path, class: :prototype__btn %>
          <%= link_to "削除する", root_path, class: :prototype__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag "プロトタイプの画像" %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= "プロトタイプのキャッチコピー" %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= "プロトタイプのコンセプト" %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%# <%= form_with model: モデル名,local: true do |f|%>
            <div class="field">
              <%# <%= f.label :hoge, "コメント" %><br />
              <%# <%= f.text_field :hoge, id:"comment_content" %>
            </div>
            <div class="actions">
              <%# <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <%# <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <%# <%= " コメントのテキスト "%>
              <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの投稿"%>
      </h2>
     
      <div class="user__card">
          <%= render partial: "places/place", collection: @places %>
      </div>
    </div>
  </div>
</div>